apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-sample
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: mycontainer=docker.io/kouki9818/my-spring-boot-app
    argocd-image-updater.argoproj.io/mycontainer.update-strategy: latest
    argocd-image-updater.argoproj.io/mycontainer.allow-tags: '*'
spec:
  project: default
  source:
    repoURL: 'https://github.com/sato9818/argocd-sample-java-app'
    path: k8s/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true