apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
data:
  log.level: debug
  registries.conf: |
    registries:
    - name: DockerHub registry
      prefix: docker.io
      api_url: https://registry-1.docker.io
      credentialsgeneric:
        secretname: regcred
        keyname: .dockerconfigjson
