apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: my-spring-boot-app=docker.io/kouki9818/my-spring-boot-app
    argocd-image-updater.argoproj.io/my-spring-boot-app.update-strategy: latest
    argocd-image-updater.argoproj.io/my-spring-boot-app.allow-tags: any
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sato9818/argocd-sample-java-app
    targetRevision: HEAD
    path: k8s/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated: {}