apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: my-spring-boot-app=docker.io/kouki9818/my-spring-boot-app
    argocd-image-updater.argoproj.io/my-spring-boot-app.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: git@github.com:sato9818/argocd-sample-java-app.git
    targetRevision: main
    path: k8s/app/child-apps/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
